
name: pollination

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_DB: master
      POSTGRES_PASSWORD: pwd

  back-end:
    container_name: back-end
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - postgres

  front-end:
    container_name: front-end
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  
