# name: E2E Test
# 
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# 
# jobs:
#   playwright:
#     timeout-minutes: 60
#     run-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pipenv
#         cd ./e2e
#         pipenv install
#     - name: Ensure browsers are installed
#       run: playwright install --with-deps
#     - name: Start docker containers
#       run: docker compose up -d
#     - name: Run Tests
#       run: pytest --tracing=retain-on-failure
#     - uses: actions/upload-artifact@4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-traces
#         path: test-results/
name: E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pipenv'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/
